import { Button } from '@/components/ui/button'
import { Github, Linkedin, Mail, User } from 'lucide-react'
import type { Metadata } from 'next'
import { ThemeProvider } from 'next-themes'
import { Geist, Geist_Mono } from 'next/font/google'
import Link from 'next/link'
import BurgerMenu from './components/burger'
import { NavLink } from './components/navlink'
import './globals.css'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased max-w-[1520px] m-auto`}
			>
				<ThemeProvider attribute='class' defaultTheme='dark' enableSystem>
					<header className=' bg-black text-white'>
						<nav className='w-[85%] m-auto flex py-[30px] justify-between items-center'>
							<p className='font-bold text-[30px] text-white tracking-[1px]'>
								My Portfolio
							</p>
							<ul className='hidden sm:flex items-center text-[18px] tracking-[1px] gap-[40px]'>
								<NavLink href='/'>
									{' '}
									<li className='text-[18px] tracking-[2px]'>Home </li>
								</NavLink>
								<NavLink href='/about'>
									<li className='text-[18px] tracking-[2px]'>About</li>{' '}
								</NavLink>
								<NavLink href='/projects'>
									<li className='text-[18px] tracking-[2px]'>Projects</li>
								</NavLink>
								<NavLink href='/contact'>
									<li className='text-[18px] tracking-[2px]'>Contact</li>{' '}
								</NavLink>
							</ul>
							<BurgerMenu />
						</nav>
					</header>
					{children}
					<footer className='border-t py-6 md:py-8'>
						<div className='container w-[85%] m-auto flex flex-col md:flex-row items-center justify-between gap-4 text-center md:text-left'>
							<div className='flex items-center gap-2 font-bold'>
								<User className='h-5 w-5' />
								<span>Portfolio</span>
							</div>
							<p className='text-sm text-muted-foreground'>
								© {new Date().getFullYear()} Your Name. All rights reserved.
							</p>
							<div className='flex items-center gap-2'>
								<Link
									href='https://github.com/Padarisigma'
									target='_blank'
									rel='noopener noreferrer'
								>
									<Button variant='ghost' size='icon'>
										<Github className='h-5 w-5' />
										<span className='sr-only'>GitHub</span>
									</Button>
								</Link>
								<Link
									href='https://linkedin.com'
									target='_blank'
									rel='noopener noreferrer'
								>
									<Button variant='ghost' size='icon'>
										<Linkedin className='h-5 w-5' />
										<span className='sr-only'>LinkedIn</span>
									</Button>
								</Link>
								<Link href='mailto:hello@example.com'>
									<Button variant='ghost' size='icon'>
										<Mail className='h-5 w-5' />
										<span className='sr-only'>Email</span>
									</Button>
								</Link>
							</div>
						</div>
					</footer>
				</ThemeProvider>
			</body>
		</html>
	)
}
